### ISSUE TITLE
使用 tmagic-editor 开发自定义组件，按照 '在管理端中引入runtime'，编辑器中组件完全空白.  

### ISSUE THREAD

**Issue by junjiantech** [vft-magic/tmagic-admin#1]
我参考 tmagic-admin 这里把产物移动到 server/static/vue3 后, 打开编辑器上边是空白的
![97f741ec5724cab9bf06bf19d86cb1e3](https://user-images.githubusercontent.com/66256045/232744211-22de34db-2306-4c2f-b288-f9fea39d4456.png)
![8c969fd3a390856c46c15b57232fa1c3](https://user-images.githubusercontent.com/66256045/232744249-d76a2225-86b1-4804-ad9a-0660be40d023.png)

**Comment by junjiantech** [comment]
已经将 build:runtime:admin 的命令修改为 
`build:runtime:admin": "pnpm --filter \"runtime-vue3\" build:admin`

目前 editor 的 runtime:vue2 存在配置问题 无法生成配置

**Comment by junjiantech** [comment]
![image](https://user-images.githubusercontent.com/66256045/232953346-b1b6c0bf-157e-4bab-8d4e-86b73293aacc.png)
实际为 'r.setDesignWidth is not a function' 找不到这个方法

**Comment by junjiantech** [comment]
**目前解决方案：**

分别在如下文件中对 core/App.ts 增加方法，防止产物找不到 setDesignWidth.

/tmagic-editor/runtime/vue3/page/main.ts
![image](https://user-images.githubusercontent.com/66256045/232953775-f57ed9da-abf1-4e64-95b6-2bfcb8a39a58.png)
/tmagic-editor/runtime/vue3/page/main.ts
![image](https://user-images.githubusercontent.com/66256045/232953843-fee1e0a5-b9dd-46a3-8de2-237fa50c14eb.png)
```
  app.calcFontsize = function() {
    const { width } = document.documentElement.getBoundingClientRect();
    const fontSize = width / (this.designWidth / 100);
    document.documentElement.style.fontSize = `${fontSize}px`;
  };

  app.setDesignWidth = function(width: number) {
    app.designWidth = width;
    // 根据屏幕大小计算出跟节点的font-size，用于rem样式的适配
    if (app.jsEngine === 'browser') {
      app.calcFontsize();
      globalThis.removeEventListener('resize', app.calcFontsize);
      globalThis.addEventListener('resize', app.calcFontsize);
    }
  };
```

**Comment by JackJeme** [comment]
@junjiantech 你可以直接在管理端中使用editor吗

**Comment by JackJeme** [comment]
> 已经将 build:runtime:admin 的命令修改为 `build:runtime:admin": "pnpm --filter \"runtime-vue3\" build:admin`
> 
> 目前 editor 的 runtime:vue2 存在配置问题 无法生成配置

请问你这个是在哪里执行的命令

**Comment by junjiantech** [comment]
> 请问你这个是在哪里执行的命令

抱歉，后续没有继续调研使用了。

build:runtime:admin 是自己写的命令，最终修改为了 "build:runtime:admin": "cd runtime && npm run build:admin && copyfiles -u 1 'dist/**/*' '../server/static/vue3/'"

项目结构大致如下：

![image](https://github.com/vft-magic/tmagic-admin/assets/66256045/410d4149-b31d-47a2-967d-d87861024853)

**Comment by JackJeme** [comment]
> > 请问你这个是在哪里执行的命令
> 
> 抱歉，后续没有继续调研使用了。
> 
> build:runtime:admin 是自己写的命令，最终修改为了 "build:runtime:admin": "cd runtime && npm run build:admin && copyfiles -u 1 'dist/**/*' '../server/static/vue3/'"
> 
> 项目结构大致如下：
> 
> ![image](https://private-user-images.githubusercontent.com/66256045/323843415-410d4149-b31d-47a2-967d-d87861024853.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDczNzgsIm5iZiI6MTcxMzUwNzA3OCwicGF0aCI6Ii82NjI1NjA0NS8zMjM4NDM0MTUtNDEwZDQxNDktYjMxZC00N2EyLTk2N2QtZDg3ODYxMDI0ODUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA2MTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZTc2NmY1YTI3Zjg3NzgyZmZjZDU3ZmUzYzIzNWMyZTAyNmJkNjNmNjlkOWU2MGFjMjM2YWZlOWUwYTkwNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4GGH435ewjUtVzrRZW0gkQJDd4xfVo9WpgzpHi0lYbE)

你是把admin搬到tmagic-editor里面用吗

**Comment by junjiantech** [comment]
> 你是把admin搬到tmagic-editor里面用吗

不是，直接根据这个 admin 修改的.  前端管理模块 web 没有动，只增加了一些常用的组件。 server 改成了上传产物到CDN，他的产物是一个 DSL文件。 DSL文件通过传递参数，动态渲染页面。 生成页面本质上就是生成DSL参数，后面也想用这个做动态生成海报的尝试... 不过没后续了

**Comment by junjiantech** [comment]
build:runtime:admin 这个指令就是让自定义的组件能在 editor 中使用.
