### ISSUE TITLE
server中需要注意的问题

### ISSUE THREAD

**Issue by toadprince** [vft-magic/tmagic-admin#2]
1、server中安装依赖时，最好使用npm命令，不要用pnpm，否则启动时会报：TSError: ⨯ Unable to compile TypeScript。
如果要使用pnpm的话，安装依赖后，重新用npm安装ts-node和typescript
npm install ts-node --save-dev
npm install ts-node --save-dev 

2、要删除server/src/service/act.ts里create方法里创建活动时，添加默认活动页的代码，否则会报config.id不能为空的错

**Comment by cloydlau** [comment]
感谢分享

**Comment by cloydlau** [comment]
@toadprince 感谢分享

**Comment by cloydlau** [comment]
感谢分享
