### ISSUE TITLE
文件 /tmagic-admin/setup.sh 不存在

### ISSUE THREAD

**Issue by PineSongCN** [vft-magic/tmagic-admin#4]
文件 /tmagic-admin/setup.sh 不存在

**Comment by jia000** [comment]
已经删掉了，这个构建脚本一般需要根据部署的实际情况来

**Comment by PineSongCN** [comment]
> 已经删掉了，这个构建脚本一般需要根据部署的实际情况来

谢谢，请问页面文档里的demo https://tencent.github.io/tmagic-editor/playground/index.html#/ 是否有示例代码？

**Comment by jia000** [comment]
https://github.com/Tencent/tmagic-editor/tree/master/playground

**Comment by PineSongCN** [comment]
> https://github.com/Tencent/tmagic-editor/tree/master/playground

谢谢，我看看
